// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uttclwtaxoxelfwyeyyp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV0dGNsd3RheG94ZWxmd3lleXlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM4MjQ2NzIsImV4cCI6MjA0OTQwMDY3Mn0.8YnuDrS815S7ppf8YnD0pzx1P6i2-NH3TnaDp-uWt9Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);